//
//  Palette.swift
//  Swatch This
//
//  Created by Russ Hooper on 7/12/20.
//  Copyright © 2020 Radio Silence. All rights reserved.
//

import Foundation

struct Palette {
    
    let masterPalette = [
        
    
        // copy in from Excel file, then replace single quotation with ". Also delete last comma. Search for Heart and replace that " with a single quote.
        // there are a few color names that have the single quotation in them; go find those and fix
        
        Colors(hex: 0x944A63, name: "Glitterati", company: "Behr®", group: "Bergundy", website: "https://www.behr.com/consumer/ColorDetailView/P120-7", pack: 0),
        Colors(hex: 0x9C6071, name: "Tropical Hibiscus", company: "Behr®", group: "Bergundy", website: "https://www.behr.com/consumer/ColorDetailView/M130-6", pack: 1),
        Colors(hex: 0x864C58, name: "Wine Not", company: "Behr®", group: "Bergundy", website: "https://www.behr.com/consumer/ColorDetailView/MQ1-02", pack: 0),
        Colors(hex: 0x995151, name: "Bricktone Red", company: "Benjamin Moore®", group: "Bergundy", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2005-30/bricktone-red?color=2005-30", pack: 1),
        Colors(hex: 0x774141, name: "Bordeaux", company: "PPG Paints®", group: "Bergundy", website: "https://www.ppgpaints.com/color/color-families/reds/bordeaux", pack: 0),
        Colors(hex: 0x773738, name: "Dinner Party", company: "Benjamin Moore®", group: "Bergundy", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/af-300/dinner-party?color=AF-300", pack: 0),
        Colors(hex: 0x744245, name: "Rumors", company: "Behr®", group: "Bergundy", website: "https://www.behr.com/consumer/ColorDetailView/MQ1-15", pack: 1),
        Colors(hex: 0x3097D0, name: "Blue Burst", company: "Valspar®", group: "Blue", website: "https://www.valspar.com/en/colors/browse-colors/lowes/blue/blue-burst-4008-10b", pack: 1),
        Colors(hex: 0x3E85BE, name: "King Triton", company: "PPG Paints®", group: "Blue", website: "https://www.ppgpaints.com/color/color-families/blues/king-triton", pack: 1),
        Colors(hex: 0x1D70AD, name: "Planetarium", company: "PPG Paints®", group: "Blue", website: "https://www.ppgpaints.com/color/color-families/blues/planetarium", pack: 1),
        Colors(hex: 0x1B5997, name: "Suddenly Sapphire", company: "PPG Paints®", group: "Blue", website: "https://www.ppgpaints.com/color/color-families/blues/suddenly-sapphire", pack: 1),
        Colors(hex: 0x265C98, name: "Beacon Blue", company: "Behr®", group: "Blue", website: "https://www.behr.com/consumer/ColorDetailView/P510-7", pack: 1),
        Colors(hex: 0x395865, name: "Deep Breath", company: "Behr®", group: "Blue", website: "https://www.behr.com/consumer/ColorDetailView/S460-7", pack: 1),
        Colors(hex: 0x213C5E, name: "Symphony Blue", company: "Benjamin Moore®", group: "Blue", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2060-10/symphony-blue?color=2060-10", pack: 0),
        Colors(hex: 0x1AA9C1, name: "High Dive", company: "Behr®", group: "Blue", website: "https://www.behr.com/consumer/ColorDetailView/P480-5", pack: 0),
        Colors(hex: 0x02819D, name: "Blue Mosque", company: "Sherwin Williams®", group: "Blue", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6789-blue-mosque", pack: 0),
        Colors(hex: 0x56B5CA, name: "Fountain", company: "Sherwin Williams®", group: "Blue", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6787-fountain", pack: 0),
        Colors(hex: 0x29545C, name: "Deep Emerald", company: "PPG Paints®", group: "Blue", website: "https://www.ppgpaints.com/color/color-families/aquas/deep-emerald", pack: 0),
        Colors(hex: 0x4C7377, name: "Vining Ivy", company: "PPG Paints®", group: "Blue", website: "https://www.ppgpaints.com/color/color-families/aquas/vining-ivy", pack: 1),
        Colors(hex: 0x57A3B3, name: "Explorer Blue", company: "Behr®", group: "Blue", website: "https://www.behr.com/consumer/colors/paint/color/M470-5", pack: 1),
        Colors(hex: 0xE36A81, name: "Cherry Brandy", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/cherry-brandy", pack: 0),
        Colors(hex: 0xC9527F, name: "Razzle Dazzle", company: "Benjamin Moore®", group: "Blush", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1348/razzle-dazzle?color=1348&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fred%2Fred", pack: 0),
        Colors(hex: 0xC94B66, name: "California Wine", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/california-wine", pack: 0),
        Colors(hex: 0xAC3E5F, name: "Heart's Desire", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/heart-s-desire", pack: 1),
        Colors(hex: 0xC2585C, name: "Bonfire", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/bonfire", pack: 1),
        Colors(hex: 0xF6CDD3, name: "Pleasing Pink", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/pleasing-pink", pack: 1),
        Colors(hex: 0xEEBFC9, name: "Rose Melody", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/rose-melody", pack: 1),
        Colors(hex: 0xF3C1C0, name: "Silver Strawberry", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/silver-strawberry", pack: 1),
        Colors(hex: 0xCEAEBB, name: "Pink Potion", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/purples/pink-potion", pack: 1),
        Colors(hex: 0xCD94BF, name: "Moorland Heather", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/purples/moorland-heather", pack: 1),
        Colors(hex: 0xE898BF, name: "Island Sunset", company: "Benjamin Moore®", group: "Blush", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1346/island-sunset?color=1346&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fred%2Fred", pack: 0),
        Colors(hex: 0xE6AAC1, name: "Little Princess", company: "Behr®", group: "Blush", website: "https://www.behr.com/consumer/ColorDetailView/P130-3", pack: 0),
        Colors(hex: 0xB88096, name: "Cabaret", company: "Behr®", group: "Blush", website: "https://www.behr.com/consumer/ColorDetailView/M130-5", pack: 0),
        Colors(hex: 0xF5B4BC, name: "Powder Rose", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/powder-rose", pack: 1),
        Colors(hex: 0xF392A1, name: "Pink Punch", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/pink-punch", pack: 0),
        Colors(hex: 0x6D9495, name: "Ship Shape", company: "Valspar®", group: "Blush", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/blue/ship-shape-v102-5", pack: 1),
        Colors(hex: 0xE59DAE, name: "Brandywine", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/brandywine", pack: 1),
        Colors(hex: 0xD2768D, name: "Razzberries", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/razzberries", pack: 1),
        Colors(hex: 0xDA7677, name: "Red Cedar", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/red-cedar", pack: 1),
        Colors(hex: 0xED9B9C, name: "River Rouge", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/pinks/river-rouge", pack: 1),
        Colors(hex: 0x996879, name: "Wild Geranium", company: "PPG Paints®", group: "Blush", website: "https://www.ppgpaints.com/color/color-families/purples/wild-geranium", pack: 1),
        Colors(hex: 0xA76943, name: "Maple Glaze", company: "Behr®", group: "Brown", website: "https://www.behr.com/consumer/ColorDetailView/PPU3-16", pack: 0),
        Colors(hex: 0xB48672, name: "Belfry Brick", company: "Valspar®", group: "Brown", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/neutral/belfry-brick-v082-4", pack: 0),
        Colors(hex: 0x905B42, name: "Spiced Cider", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/oranges/spiced-cider", pack: 1),
        Colors(hex: 0x9D6755, name: "Warm Up", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/oranges/warm-up", pack: 1),
        Colors(hex: 0x60443F, name: "Death by Chocolate", company: "Behr®", group: "Brown", website: "https://www.behr.com/consumer/ColorDetailView/MQ1-54", pack: 0),
        Colors(hex: 0x684345, name: "Twinberry", company: "Behr®", group: "Brown", website: "https://www.behr.com/consumer/ColorDetailView/MQ1-14", pack: 0),
        Colors(hex: 0x70554A, name: "Carmelized Walnut", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/beiges/caramelized-walnut", pack: 1),
        Colors(hex: 0x4E3B34, name: "Coffee Date", company: "Clare®", group: "Brown", website: "https://www.clare.com/paint/wall/coffee-date", pack: 1),
        Colors(hex: 0x5F4B42, name: "Little Bear", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/beiges/little-bear", pack: 0),
        Colors(hex: 0x977D6F, name: "Peppered Pecan", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/neutrals/peppered-pecan", pack: 0),
        Colors(hex: 0xC09E73, name: "Peanut Shell", company: "Benjamin Moore®", group: "Brown", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2162-40/peanut-shell?color=2162-40", pack: 0),
        Colors(hex: 0x524B59, name: "Shadow", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2117-30/shadow?color=2117-30", pack: 0),
        Colors(hex: 0x3F4D5A, name: "Calvary", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/cavalry", pack: 1),
        Colors(hex: 0x434B56, name: "Hale Navy", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/hc-154/hale-navy?color=HC-154", pack: 1),
        Colors(hex: 0x474B51, name: "Baby Seal Black", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2119-30/baby-seal-black?color=2119-30", pack: 1),
        Colors(hex: 0x41414B, name: "Napoleon", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/napoleon", pack: 1),
        Colors(hex: 0x575553, name: "Iron Mountain", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2134-30/iron-mountain?color=2134-30&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fbla%2Fblack", pack: 1),
        Colors(hex: 0x42444B, name: "Abyss", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2128-20/abyss?color=2128-20&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fbla%2Fblack", pack: 1),
        Colors(hex: 0x4C4F52, name: "French Beret", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1610/french-beret?color=1610&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fbla%2Fblack", pack: 1),
        Colors(hex: 0x413F40, name: "Black Magic", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/black-magic", pack: 1),
        Colors(hex: 0x626463, name: "City Shadow", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/csp-60/city-shadow?color=CSP-60&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fgra%2Fgray", pack: 0),
        Colors(hex: 0x696867, name: "Overcoat", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/cc-544/overcoat?color=CC-544", pack: 0),
        Colors(hex: 0x525F68, name: "Goblin", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/goblin", pack: 1),
        Colors(hex: 0x535E63, name: "Mysterious", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/mysterious", pack: 1),
        Colors(hex: 0x575E5F, name: "Mostly Metal", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/mostly-metal", pack: 1),
        Colors(hex: 0x676858, name: "Double Duty", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/greens/double-duty", pack: 1),
        Colors(hex: 0x76745D, name: "Positively Palm", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/greens/positively-palm", pack: 1),
        Colors(hex: 0x585861, name: "Gray Flannel", company: "PPG Paints®", group: "Dark Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/gray-flannel", pack: 0),
        Colors(hex: 0x4B6443, name: "Deep Viridian", company: "Behr®", group: "Green", website: "https://www.behr.com/consumer/ColorDetailView/S400-7", pack: 1),
        Colors(hex: 0x658362, name: "Tuscan Herbs", company: "Behr®", group: "Green", website: "https://www.behr.com/consumer/ColorDetailView/S400-6", pack: 1),
        Colors(hex: 0x3A5649, name: "Black Spruce", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/black-spruce", pack: 1),
        Colors(hex: 0x037844, name: "Blarney Stone", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/blarney-stone", pack: 1),
        Colors(hex: 0x7A8C31, name: "Sassy Grass", company: "Behr®", group: "Green", website: "https://www.behr.com/consumer/ColorDetailView/P360-7", pack: 1),
        Colors(hex: 0x80905F, name: "Green Energy", company: "Behr®", group: "Green", website: "https://www.behr.com/consumer/ColorDetailView/PPU10-03", pack: 1),
        Colors(hex: 0x288F50, name: "Once Upon a Time", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/574/once-upon-a-time?color=574&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fgre%2Fgreen", pack: 0),
        Colors(hex: 0x67B458, name: "Paradise Valley", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/559/paradise-valley?color=559&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fgre%2Fgreen", pack: 0),
        Colors(hex: 0x57AA80, name: "Julep", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6746-julep", pack: 0),
        Colors(hex: 0x358C3F, name: "Envy", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6925-envy", pack: 0),
        Colors(hex: 0x5EB56A, name: "Lawn Party", company: "Behr®", group: "Green", website: "https://www.behr.com/consumer/ColorDetailView/P390-6", pack: 0),
        Colors(hex: 0x6AAF82, name: "Elf Shoe", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/elf-shoe", pack: 1),
        Colors(hex: 0x519D6E, name: "Basil Pesto", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/basil-pesto", pack: 1),
        Colors(hex: 0x1FB395, name: "Aloha", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/aloha", pack: 1),
        Colors(hex: 0xB2C215, name: "Center Stage", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6920-center-stage", pack: 1),
        Colors(hex: 0x8CBF6F, name: "Laudable Lime", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/painting-contractors/color/find-and-explore-colors/paint-colors-by-family/SW6930-laudable-lime", pack: 1),
        Colors(hex: 0x7EC083, name: "Rally Green", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/painting-contractors/color/find-and-explore-colors/paint-colors-by-family/SW6934-rally-green", pack: 1),
        Colors(hex: 0xBFE8AA, name: "Shimmering Lime", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2030-50/shimmering-lime?color=2030-50&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fgre%2Fgreen", pack: 1),
        Colors(hex: 0xDAE6A6, name: "Mermaid Tears", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/mermaid-tears", pack: 1),
        Colors(hex: 0x60B1A9, name: "Artesian Well", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/aquas/artesian-well", pack: 1),
        Colors(hex: 0x007B74, name: "Romantic Isle", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/aquas/romantic-isle", pack: 1),
        Colors(hex: 0x7A999C, name: "Cathedral Glass", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/aquas/cathedral-glass", pack: 1),
        Colors(hex: 0xBCAF64, name: "Pistachio", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/MQ4-42", pack: 1),
        Colors(hex: 0x616787, name: "Binary Star", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/N450-6", pack: 0),
        Colors(hex: 0x78888E, name: "Norwegian Blue", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/N470-5", pack: 0),
        Colors(hex: 0x888D8F, name: "Hearthstone", company: "Benjamin Moore®", group: "Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1601/hearthstone?color=1601&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fgra%2Fgray", pack: 0),
        Colors(hex: 0x818387, name: "Mission Control", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/N530-5", pack: 1),
        Colors(hex: 0x8A9192, name: "Gotham Gray", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/MQ5-29", pack: 1),
        Colors(hex: 0x828388, name: "Victorian Pewter", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/victorian-pewter", pack: 1),
        Colors(hex: 0x8E9CA8, name: "Lost At Sea", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/lost-at-sea", pack: 1),
        Colors(hex: 0x89918B, name: "Gray Heron", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/gray-heron", pack: 0),
        Colors(hex: 0x8F9082, name: "Thames Fog", company: "Valspar®", group: "Greige", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/gray/thames-fog-v144-5", pack: 1),
        Colors(hex: 0xA4A085, name: "Dry Sage", company: "Benjamin Moore®", group: "Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2142-40/dry-sage?color=2142-40", pack: 1),
        Colors(hex: 0x9DA289, name: "Edamame", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/greens/edamame", pack: 1),
        Colors(hex: 0x94897C, name: "Art District", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/MQ2-57", pack: 1),
        Colors(hex: 0xD4C3AC, name: "Beach Dune", company: "Valspar®", group: "Greige", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/neutral/beach-dune-v134-2", pack: 0),
        Colors(hex: 0xD3BC9C, name: "Pony Tail", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/beiges/pony-tail", pack: 1),
        Colors(hex: 0xADB0B5, name: "Silver Charm", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/silver-charm", pack: 0),
        Colors(hex: 0xA9B8BB, name: "Lagoon Reflection", company: "Valspar®", group: "Greige", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/gray/lagoon-reflection-v139-3", pack: 1),
        Colors(hex: 0xA6B2B7, name: "Special Delivery", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/special-delivery", pack: 1),
        Colors(hex: 0xBCAFA2, name: "Barista", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/N210-3", pack: 1),
        Colors(hex: 0xB9A795, name: "Eiffel For You", company: "Behr®", group: "Greige", website: "https://www.behr.com/consumer/ColorDetailView/MQ2-37", pack: 0),
        Colors(hex: 0xBCA998, name: "Notorious", company: "PPG Paints®", group: "Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/notorious", pack: 0),
        Colors(hex: 0xB0A5A4, name: "Mystical Gray", company: "Valspar®", group: "Greige", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/neutral/mystical-gray-v127-4", pack: 0),
        Colors(hex: 0xC8AEB0, name: "Mediterranean Sunset", company: "Valspar®", group: "Blush", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/red/mediterranean-sunset-v078-3", pack: 1),
        Colors(hex: 0x908E72, name: "Wethersfield Moss", company: "Benjamin Moore®", group: "Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/hc-110/wethersfield-moss?color=HC-110", pack: 1),
        Colors(hex: 0xD2DFEA, name: "Ice Drop", company: "Behr®", group: "Light Blue", website: "https://www.behr.com/consumer/ColorDetailView/M530-1", pack: 0),
        Colors(hex: 0xD2E7ED, name: "Crystalline", company: "Valspar®", group: "Light Blue", website: "https://www.valspar.com/en/colors/browse-colors/lowes/blue/crystalline-5002-9a", pack: 0),
        Colors(hex: 0xBBCEE0, name: "Barking Creek", company: "Valspar®", group: "Light Blue", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/blue/barking-creek-v110-3", pack: 0),
        Colors(hex: 0x9CD5E6, name: "Infinity Pool", company: "Valspar®", group: "Light Blue", website: "https://www.valspar.com/en/colors/browse-colors/lowes/blue/infinity-pool-5003-9c", pack: 1),
        Colors(hex: 0xC5E5E4, name: "Swan Lake", company: "PPG Paints®", group: "Light Blue", website: "https://www.ppgpaints.com/color/color-families/aquas/swan-lake", pack: 1),
        Colors(hex: 0xB5DDDA, name: "Minerva", company: "PPG Paints®", group: "Light Blue", website: "https://www.ppgpaints.com/color/color-families/aquas/minerva", pack: 1),
        Colors(hex: 0x96D0D1, name: "Big Surf", company: "Behr®", group: "Light Blue", website: "https://www.behr.com/consumer/ColorDetailView/M460-3", pack: 0),
        Colors(hex: 0xC8DCD4, name: "Ocean Silk", company: "Valspar®", group: "Light Blue", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/blue/ocean-silk-v064-1", pack: 1),
        Colors(hex: 0xCADADA, name: "Cosmic Rays", company: "PPG Paints®", group: "Light Blue", website: "https://www.ppgpaints.com/color/color-families/aquas/cosmic-rays", pack: 1),
        Colors(hex: 0xBFC0C2, name: "Whirlwind", company: "PPG Paints®", group: "Light Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/whirlwind", pack: 1),
        Colors(hex: 0xB6B9B6, name: "Lunar Surface", company: "Behr®", group: "Light Greige", website: "https://www.behr.com/consumer/ColorDetailView/N460-3", pack: 1),
        Colors(hex: 0xCBCCC6, name: "Stonington Gray", company: "Benjamin Moore®", group: "Light Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/hc-170/stonington-gray?color=HC-170", pack: 1),
        Colors(hex: 0xCDC3BD, name: "Manchester Tan", company: "Benjamin Moore®", group: "Light Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/hc-81/manchester-tan?color=HC-81", pack: 1),
        Colors(hex: 0xD0CCC1, name: "Whiskers", company: "PPG Paints®", group: "Light Greige", website: "https://www.ppgpaints.com/color/color-families/neutrals/whiskers", pack: 1),
        Colors(hex: 0xD1D2C0, name: "Brainstorm", company: "PPG Paints®", group: "Light Greige", website: "https://www.ppgpaints.com/color/color-families/greens/brainstorm", pack: 1),
        Colors(hex: 0xC3C6B1, name: "Pale Pine", company: "PPG Paints®", group: "Light Greige", website: "https://www.ppgpaints.com/color/color-families/greens/pale-pine", pack: 1),
        Colors(hex: 0xE2D5C2, name: "Neutral Territory", company: "Clare®", group: "Light Greige", website: "https://www.clare.com/paint/wall/neutral-territory", pack: 1),
        Colors(hex: 0xD4B7B8, name: "Bombay Pink", company: "Valspar®", group: "Light Greige", website: "https://www.valspar.com/en/colors/browse-colors/lowes/neutral/bombay-pink-1006-8b", pack: 1),
        Colors(hex: 0xBDB98F, name: "Back to Nature", company: "Behr®", group: "Light Greige", website: "https://www.behr.com/consumer/ColorDetailView/S340-4", pack: 1),
        Colors(hex: 0xFDA471, name: "Cheerful Tangerine", company: "Behr®", group: "Orange", website: "https://www.behr.com/consumer/ColorDetailView/P210-5", pack: 0),
        Colors(hex: 0xFFB14F, name: "Splendor Gold", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/P250-6", pack: 0),
        Colors(hex: 0xDB7842, name: "Japanese Koi", company: "Behr®", group: "Orange", website: "https://www.behr.com/consumer/ColorDetailView/P210-7", pack: 0),
        Colors(hex: 0xE47237, name: "Invigorate", company: "Sherwin Williams®", group: "Orange", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6886-invigorate", pack: 0),
        Colors(hex: 0xD57E52, name: "Copper Harbor", company: "Sherwin Williams®", group: "Orange", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6634-copper-harbor", pack: 0),
        Colors(hex: 0xF9A48F, name: "Coral Serenade", company: "PPG Paints®", group: "Orange", website: "https://www.ppgpaints.com/color/color-families/oranges/coral-serenade", pack: 1),
        Colors(hex: 0x6D4052, name: "Chilled Wine", company: "PPG Paints®", group: "Purple", website: "https://www.ppgpaints.com/color/color-families/purples/chilled-wine", pack: 1),
        Colors(hex: 0xAD6FA0, name: "Mulberry Bush", company: "PPG Paints®", group: "Purple", website: "https://www.ppgpaints.com/color/color-families/purples/mulberry-bush", pack: 1),
        Colors(hex: 0x905185, name: "Grape Juice", company: "PPG Paints®", group: "Purple", website: "https://www.ppgpaints.com/color/color-families/purples/grape-juice", pack: 1),
        Colors(hex: 0x635083, name: "Your Majesty", company: "Benjamin Moore®", group: "Purple", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1400/your-majesty?color=1400&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fpur%2Fpurple", pack: 1),
        Colors(hex: 0x6C598D, name: "Seduction", company: "Benjamin Moore®", group: "Purple", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1399/seduction?color=1399&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor%2F1400%2Fyour-majesty", pack: 1),
        Colors(hex: 0x8B2829, name: "Caliente", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/af-290/caliente?color=AF-290", pack: 0),
        Colors(hex: 0xD04838, name: "Top Tomato", company: "Behr®", group: "Red", website: "https://www.behr.com/consumer/ColorDetailView/P180-7", pack: 0),
        Colors(hex: 0xB9493E, name: "Sriracha", company: "Clare®", group: "Red", website: "https://www.clare.com/paint/trim/sriracha", pack: 1),
        Colors(hex: 0xE65458, name: "Rose Quartz", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2002-30/rose-quartz?color=2002-30&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fred%2Fred", pack: 0),
        Colors(hex: 0xC93F37, name: "100 MPH", company: "Behr®", group: "Red", website: "https://www.behr.com/consumer/ColorDetailView/P170-7", pack: 0),
        Colors(hex: 0x9F403E, name: "Burning Bush", company: "PPG Paints®", group: "Red", website: "https://www.ppgpaints.com/color/color-families/reds/burning-bush", pack: 1),
        Colors(hex: 0xBE3C37, name: "Flirt Alert", company: "Behr®", group: "Red", website: "https://www.behr.com/consumer/ColorDetailView/P150-7", pack: 1),
        Colors(hex: 0xDF745A, name: "Rustic Pottery", company: "PPG Paints®", group: "Red", website: "https://www.ppgpaints.com/color/color-families/oranges/rustic-pottery", pack: 1),
        Colors(hex: 0xC9533A, name: "Cinnamon Stone", company: "PPG Paints®", group: "Red", website: "https://www.ppgpaints.com/color/color-families/oranges/cinnamon-stone", pack: 1),
        Colors(hex: 0xF4D8D6, name: "Scented Valentine", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/pinks/scented-valentine", pack: 1),
        Colors(hex: 0xF4DFB6, name: "Belgian Waffle", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/yellows/belgian-waffle", pack: 1),
        Colors(hex: 0xD8DCDD, name: "Spring Thaw", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/neutrals/spring-thaw", pack: 1),
        Colors(hex: 0xF4E4E5, name: "Gaiety", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/pinks/gaiety", pack: 1),
        Colors(hex: 0xD9CBBE, name: "Bermuda Sand", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/neutrals/bermuda-sand", pack: 0),
        Colors(hex: 0xF3E9D6, name: "Ceylon Cream", company: "Behr®", group: "White", website: "https://www.behr.com/consumer/ColorDetailView/HDC-CL-17", pack: 0),
        Colors(hex: 0xECD9CA, name: "Nutmeg Frost", company: "Behr®", group: "White", website: "https://www.behr.com/consumer/ColorDetailView/S210-1", pack: 0),
        Colors(hex: 0xF7F1E1, name: "Coconut Twist", company: "Behr®", group: "White", website: "https://www.behr.com/consumer/ColorDetailView/GR-W14", pack: 0),
        Colors(hex: 0xFAF3E4, name: "Mayonnaise", company: "Benjamin Moore®", group: "White", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/oc-85/mayonnaise?color=OC-85", pack: 0),
        Colors(hex: 0xF2E9CF, name: "Spice Delight", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/yellows/spice-delight", pack: 1),
        Colors(hex: 0xF2F0E2, name: "Accolade", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/whites/accolade", pack: 1),
        Colors(hex: 0xE5E7E6, name: "Radisson", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/neutrals/radisson", pack: 1),
        Colors(hex: 0xEEE6DB, name: "Pearls And Lace", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/neutrals/pearls-and-lace", pack: 1),
        Colors(hex: 0xEAE0D4, name: "Moroccan Moonlight", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/neutrals/moroccan-moonlight", pack: 1),
        Colors(hex: 0xE3E2C1, name: "Ethereal One", company: "Valspar®", group: "White", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/green/ethereal-one-v058-1", pack: 1),
        Colors(hex: 0xE0D6CE, name: "Romantic White", company: "Valspar®", group: "White", website: "https://www.valspar.com/en/colors/browse-colors/independent-retailers/neutral/romantic-white-v129-1", pack: 1),
        Colors(hex: 0xD1E5D7, name: "Peppermint Patty", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/greens/peppermint-patty", pack: 1),
        Colors(hex: 0xDCE2E9, name: "First Frost", company: "PPG Paints®", group: "White", website: "https://www.ppgpaints.com/color/color-families/blues/first-frost", pack: 1),
        Colors(hex: 0xC08F34, name: "Turmeric", company: "Behr®", group: "Brown", website: "https://www.behr.com/consumer/ColorDetailView/M290-7", pack: 0),
        Colors(hex: 0xCE9945, name: "Mayan Treasure", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/yellows/mayan-treasure", pack: 0),
        Colors(hex: 0xBA852F, name: "Gothic Gold", company: "PPG Paints®", group: "Brown", website: "https://www.ppgpaints.com/color/color-families/yellows/gothic-gold", pack: 0),
        Colors(hex: 0xEAB034, name: "Midsummer Gold", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/P280-7", pack: 0),
        Colors(hex: 0xDEAC5C, name: "Brown Mustard", company: "PPG Paints®", group: "Yellow", website: "https://www.ppgpaints.com/color/color-families/yellows/brown-mustard", pack: 0),
        Colors(hex: 0xE5C269, name: "Hannah Banana", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/csp-955/hannah-banana?color=CSP-955&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fyel%2Fyellow", pack: 0),
        Colors(hex: 0xE3BB65, name: "Dandelion Wish", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/MQ4-12", pack: 0),
        Colors(hex: 0xEBC27D, name: "York Harbor Yellow", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2154-40/york-harbor-yellow?color=2154-40", pack: 0),
        Colors(hex: 0xEBC482, name: "Gold Buff", company: "PPG Paints®", group: "Yellow", website: "https://www.ppgpaints.com/color/color-families/yellows/gold-buff", pack: 0),
        Colors(hex: 0xFFCE0C, name: "Sunshine", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2021-30/sunshine?color=2021-30&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fyel%2Fyellow", pack: 1),
        Colors(hex: 0xE1BD1B, name: "Laser Lemon", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/P290-7", pack: 1),
        Colors(hex: 0xF8D60A, name: "Sun Porch", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2023-30/sun-porch?color=2023-30&source=%2Fen-us%2Fcolor-overview%2Ffind-your-color%2Fcolor-families%2Fyel%2Fyellow", pack: 1),
        Colors(hex: 0xFFE487, name: "Upbeat", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/P300-5", pack: 1),
        Colors(hex: 0xFFD467, name: "Squash Blossom", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/P290-5", pack: 1),
        Colors(hex: 0xFFC819, name: "Unmellow Yellow", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/P300-7", pack: 1),
        Colors(hex: 0xFFB302, name: "Saffron Thread", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/310B-7", pack: 1),
        Colors(hex: 0xFFBD24, name: "Macaw", company: "Behr®", group: "Yellow", website: "https://www.behr.com/consumer/ColorDetailView/320B-7", pack: 1),
        Colors(hex: 0x5C7CB4, name: "Bright Cornflower", company: "Glidden®", group: "Blue", website: "https://www.glidden.com/colors/blue/bright-cornflower-blue", pack: 1),
        Colors(hex: 0x6B869D, name: "Blue Nose", company: "Benjamin Moore®", group: "Blue", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/1678/blue-nose?color=1678", pack: 1),
        Colors(hex: 0xB8D5E4, name: "Something Blue", company: "Sherwin Williams®", group: "Light Blue", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6800-something-blue", pack: 1),
        Colors(hex: 0x6CA1C2, name: "Rolling Sea", company: "Valspar®", group: "Blue", website: "https://www.valspar.com/en/colors/browse-colors/lowes/blue/rolling-sea-5001-10b", pack: 1),
        Colors(hex: 0xCEE4EA, name: "Winterscape", company: "Behr®", group: "Light Blue", website: "https://www.behr.com/consumer/ColorDetailView/M480-2A/", pack: 1),
        Colors(hex: 0xB1C67E, name: "Stem Green", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/2029-40/stem-green?color=2029-40", pack: 1),
        Colors(hex: 0x98AA4F, name: "Sassy Green", company: "Valspar®", group: "Green", website: "https://www.valspar.com/en/colors/browse-colors/lowes/green/sassy-green-6009-10", pack: 1),
        Colors(hex: 0xB3B066, name: "Parakeet", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6711-parakeet", pack: 1),
        Colors(hex: 0x2F2F30, name: "Tricorn Black", company: "Sherwin Williams®", group: "Dark Greige", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6258-tricorn-black", pack: 1),
        Colors(hex: 0xC4D0CA, name: "Woodlawn Blue", company: "Benjamin Moore®", group: "Light Blue", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/hc-147/woodlawn-blue?color=HC-147", pack: 1),
        Colors(hex: 0xC47738, name: "Carrots", company: "Benjamin Moore®", group: "Orange", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/csp-1110/14-carrots?color=CSP-1110", pack: 1),
        Colors(hex: 0x5C6956, name: "Peale Green", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/hc-121/peale-green?color=HC-121", pack: 1),
        Colors(hex: 0x69635E, name: "Coachman's Cape", company: "Benjamin Moore®", group: "Dark Greige", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/csp-90/coachmans-cape?color=CSP-90", pack: 1),
        Colors(hex: 0x4B5780, name: "Yacht Club Blue", company: "Behr®", group: "Purple", website: "https://www.behr.com/consumer/ColorDetailView/600B-7/", pack: 1),
        Colors(hex: 0xD77343, name: "Island Orange", company: "Valspar®", group: "Orange", website: "https://www.valspar.com/en/colors/browse-colors/lowes/orange/island-orange-2010-2", pack: 1),
        Colors(hex: 0xD26B4C, name: "Autumn Blaze", company: "Valspar®", group: "Orange", website: "https://www.valspar.com/en/colors/browse-colors/lowes/orange/autumn-blaze-2002-1a", pack: 1),
        Colors(hex: 0xE79359, name: "Fresh Persimmons", company: "Valspar®", group: "Orange", website: "https://www.valspar.com/en/colors/browse-colors/lowes/orange/fresh-persimmons-2009-1", pack: 1),
        Colors(hex: 0xEBD9E4, name: "Lucky You", company: "Valspar®", group: "Blush", website: "https://www.valspar.com/en/colors/browse-colors/lowes/purple/lucky-you-1004-4c", pack: 1),
        Colors(hex: 0x8B80B6, name: "Grapolicious", company: "Valspar®", group: "Purple", website: "https://www.valspar.com/en/colors/browse-colors/lowes/purple/grapolicious-4003-10b", pack: 1),
        Colors(hex: 0xBC6FA4, name: "Cosmic Pink", company: "Valspar®", group: "Purple", website: "https://www.valspar.com/en/colors/browse-colors/lowes/purple/cosmic-pink-1001-1a", pack: 1),
        Colors(hex: 0x53446E, name: "Sumptuous Purple", company: "Valspar®", group: "Purple", website: "https://www.valspar.com/en/colors/browse-colors/lowes/purple/sumptuous-purple-4010-10", pack: 1),
        Colors(hex: 0x9FC7D1, name: "Idyllic Isle", company: "PPG Paints®", group: "Blue", website: "https://www.ppgpaints.com/color/color-families/blues/idyllic-isle", pack: 1),
        Colors(hex: 0x8C1F1D, name: "Heritage Red", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/color-overview/find-your-color/color/pm-18/heritage-red?color=PM-18", pack: 1),
        Colors(hex: 0xE28E83, name: "Debutante", company: "Pratt & Lambert®", group: "Blush", website: "https://www.prattandlambert.com/?s=debutante#F0897F-38", pack: 1),
        Colors(hex: 0x5E84A1, name: "Hemisphere", company: "Behr®", group: "Blue", website: "https://www.behr.com/consumer/ColorDetailView/M500-4/", pack: 1),
        Colors(hex: 0x345D3A, name: "Derbyshire", company: "Sherwin Williams®", group: "Green", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW6741-derbyshire", pack: 1),
        Colors(hex: 0x92943F, name: "Lazy Lizard", company: "Behr®", group: "Green", website: "https://www.behr.com/consumer/ColorDetailView/P350-7", pack: 1),
        Colors(hex: 0x9CAD62, name: "Asparagus", company: "PPG Paints®", group: "Green", website: "https://www.ppgpaints.com/color/color-families/greens/asparagus", pack: 1),
        Colors(hex: 0x408F95, name: "Azure Tide", company: "Sherwin Williams®", group: "Blue", website: "https://www.sherwin-williams.com/homeowners/color/find-and-explore-colors/paint-colors-by-family/SW9684-azure-tide", pack: 1),
        Colors(hex: 0xF9DB88, name: "Birdsong", company: "Pratt & Lambert®", group: "Yellow", website: "https://www.prattandlambert.com/?s=birdsong", pack: 1),
        Colors(hex: 0xC6B0A3, name: "Cappuccino", company: "Benjamin Moore®", group: "Brown", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2096-50/cappuccino", pack: 0),
        Colors(hex: 0x99B0BB, name: "Saratoga Springs", company: "Benjamin Moore®", group: "Blue", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/1669/saratoga-springs", pack: 0),
        Colors(hex: 0xA5B0AE, name: "Mount Saint Anne", company: "Benjamin Moore®", group: "Blue", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/cc-710/mount-saint-anne", pack: 1),
        Colors(hex: 0xB47468, name: "Wild Flower", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2090-40/wild-flower", pack: 1),
        Colors(hex: 0x376875, name: "Varsity Blues", company: "Benjamin Moore®", group: "Blue", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/756/varsity-blues", pack: 1),
        Colors(hex: 0x4A7983, name: "Calypso Blue", company: "Benjamin Moore®", group: "Blue", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/727/calypso-blue", pack: 1),
        Colors(hex: 0xD8DAB2, name: "Warren Acres", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/527/warren-acres", pack: 1),
        Colors(hex: 0xC0C28D, name: "Sweet Daphne", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/529/sweet-daphne", pack: 1),
        Colors(hex: 0xA1A46D, name: "Medieval Times", company: "Benjamin Moore®", group: "Green", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/530/medieval-times", pack: 1),
        Colors(hex: 0x943D5E, name: "Royal Flush", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2076-20/royal-flush", pack: 1),
        Colors(hex: 0x9C313F, name: "Candy Cane Red", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2079-10/candy-cane-red", pack: 1),
        Colors(hex: 0xAD4A56, name: "Drop Dead Gorgeous", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/1329/drop-dead-gorgeous", pack: 1),
        Colors(hex: 0xE7AECA, name: "Rhododendron", company: "Benjamin Moore®", group: "Blush", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2079-50/rhododendron", pack: 1),
        Colors(hex: 0xE29C9F, name: "Heartbeat", company: "Benjamin Moore®", group: "Blush", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/1319/heartbeat", pack: 1),
        Colors(hex: 0x9C3D39, name: "Hot Tamale", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/csp-1155/hot-tamale", pack: 1),
        Colors(hex: 0xC44645, name: "Bonfire", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2001-20/bonfire", pack: 0),
        Colors(hex: 0xF4B54B, name: "Citrus Blast", company: "Benjamin Moore®", group: "Orange", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2018-30/citrus-blast", pack: 1),
        Colors(hex: 0xF9D978, name: "American Cheese", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2019-40/american-cheese", pack: 1),
        Colors(hex: 0xFADF77, name: "Yellow Highlighter", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2021-40/yellow-highlighter", pack: 0),
        Colors(hex: 0xBC9C5A, name: "Antique Bronze", company: "Benjamin Moore®", group: "Yellow", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/217/antique-bronze", pack: 1),
        Colors(hex: 0xDACAAF, name: "Alpaca", company: "Benjamin Moore®", group: "Brown", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/1074/alpaca", pack: 0),
        Colors(hex: 0xD75F56, name: "Raspberry Blush", company: "Benjamin Moore®", group: "Red", website: "https://www.benjaminmoore.com/en-us/paint-colors/color/2008-30/raspberry-blush", pack: 0)
        
    ]
    
    
    
    
    
    struct Colors {
        
        let hex: UInt32
        let name: String
        let company: String
        let group: String
        let website: String
        let pack: Int


        init(hex: UInt32, name: String, company: String, group: String, website: String, pack: Int) {
            
            self.hex = hex
            self.name = name
            self.company = company
            self.group = group
            self.website = website
            self.pack = pack

        }
    }
    
    
}
